name: Build and Upload WebGL

on:
  push:
    branches:
      - main
      - SDKWithDemoProject

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      UPLOAD_URL: "https://a.messagedisco.com/api/management/games/d3d29990-a6f6-44b1-b5ac-150688526b13/upload-build"
      UPLOAD_TOKEN: ${{ secrets.GAME_UPLOAD_TOKEN }}
      BASE_VERSION: "1.0"

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v3
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      # 2. Get and increment the patch version
      - name: Compute next build version
        id: version
        run: |
          LAST_TAG=$(git tag --list "${BASE_VERSION}.*" | sort -V | tail -n1)

          if [ -z "$LAST_TAG" ]; then
            NEXT_VERSION="${BASE_VERSION}.3"   # ✅ starts at .3
          else
            PATCH=${LAST_TAG##*.}
            NEXT_PATCH=$((PATCH + 1))
            NEXT_VERSION="${BASE_VERSION}.${NEXT_PATCH}"
          fi

          echo "NEXT_VERSION=$NEXT_VERSION" | tee -a $GITHUB_ENV
          echo "Using version: $NEXT_VERSION"

      # ✅ Licensed Unity Builder (uses encoded license)
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          projectPath: UnityDemo
          versioning: None
          customImage: "unityci/editor:ubuntu-6000.0.46f1-webgl-3.1.0"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # Only include these if you're using Unity ID login-based activation
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # ✅ Zip from UnityDemo/build/WebGL
      - name: Zip build
        run: |
          cd UnityDemo/build/WebGL
          zip -r game.zip .

      # ✅ Upload using curl
      - name: Upload build
        run: |
          curl -X POST \
            -H "X-Game-Upload-Token: $UPLOAD_TOKEN" \
            -H "X-Build-Version: $NEXT_VERSION" \
            --form file=@UnityDemo/build/WebGL/game.zip \
            "$UPLOAD_URL"
