name: Build and Upload WebGL

on:
  push:
    branches:
      - main
      - SDKWithDemoProject

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      UPLOAD_URL: "https://a.messagedisco.com/api/management/games/d3d29990-a6f6-44b1-b5ac-150688526b13/upload-build"
      UPLOAD_TOKEN: ${{ secrets.GAME_UPLOAD_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: UnityDemo/Library
          key: Library-WebGL
          restore-keys: Library-
      # Free up disk space
      - name: Free Disk Space for Android
        run: |
          echo "Disabling and removing swap"
          sudo swapoff -a || true
          sudo rm -f /swapfile || true

          echo "Cleaning APT cache"
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

          echo "Pruning unused docker images"
          docker image prune -af
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android

          echo "Disk space after cleanup:"
          df -h
      - name: Build Unity WebGL
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: UnityDemo
          versioning: Semantic
          customImage: "unityci/editor:ubuntu-6000.2.3f1-webgl-3.2.0"

      - name: Print version
        run: echo "Version is ${{ steps.build.outputs.buildVersion }}"

      - name: List workspace contents
        run: ls -R .
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/WebGL
      - name: Create ZIP for upload
        run: |
          mkdir -p build_zip
          cd build
          zip -r ../build_zip/game.zip WebGL

      - name: Upload build
        run: |
          curl -X POST \
            -H "X-Game-Upload-Token: $UPLOAD_TOKEN" \
            -H "X-Build-Version: ${{ steps.build.outputs.buildVersion }}" \
            --form file=@build_zip/game.zip \
            "$UPLOAD_URL"
