name: Release on Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      version: ${{ github.ref_name }}
      build_suffix: 1
    secrets:
      GAME_UPLOAD_URL: ${{ secrets.GAME_UPLOAD_URL }}
      GAME_UPLOAD_TOKEN: ${{ secrets.GAME_UPLOAD_TOKEN }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG with commit messages
        run: |
          FILE="jest-unity-sdk/CHANGELOG.md"
          VERSION="${{ steps.version.outputs.version }}"
          DATE=$(date +"%Y-%m-%d")

          if [ ! -f "$FILE" ]; then
            echo "# Changelog" > "$FILE"
            echo "" >> "$FILE"
          fi

          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --no-merges --pretty=format:"- %s")
          else
            COMMITS=$(git log $PREV_TAG..HEAD --no-merges --pretty=format:"- %s")
          fi

          echo "" >> "$FILE"
          echo "## [$VERSION] - $DATE" >> "$FILE"
          echo "$COMMITS" >> "$FILE"

      - name: Commit and push changelog
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add jest-unity-sdk/CHANGELOG.md
          git commit -m "Update CHANGELOG for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          draft: false
          body: |
            UPM Install URL:
            https://github.com/${{ github.repository }}.git?path=jest-unity-sdk#${{ steps.version.outputs.version }}
